const typography = require('@tailwindcss/typography')

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#ffb3ad',
        'surface-tint': '#b22a2b',
        'on-background': '#1c1c18',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#5d4037',
        'secondary-container': '#fed65b',
        'on-surface-variant': '#5a403c',
        'tertiary-fixed-dim': '#e7bdb1',
        outline: '#8e706b',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#e9c349',
        'on-surface': '#1c1c18',
        tertiary: '#40261e',
        'primary-fixed-dim': '#ffb3ad',
        'inverse-surface': '#31312c',
        'outline-variant': '#e3beb8',
        'tertiary-fixed': '#ffdbd0',
        'on-secondary': '#ffffff',
        background: '#fcf9f2',
        'on-error': '#ffffff',
        'surface-dim': '#dcdad3',
        'on-primary-container': '#ff8f88',
        'error-container': '#ffdad6',
        'surface-container-high': '#ebe8e1',
        'inverse-on-surface': '#f3f0ea',
        'surface-container-highest': '#e5e2db',
        'on-primary': '#ffffff',
        'on-secondary-container': '#745c00',
        'on-primary-fixed-variant': '#8f0d17',
        'primary-container': '#890613',
        surface: '#fcf9f2',
        'surface-variant': '#e5e2db',
        'primary-fixed': '#ffdad7',
        primary: '#610008',
        'on-tertiary-container': '#cea79b',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#ffe088',
        'on-primary-fixed': '#410004',
        'on-tertiary-fixed': '#2c160e',
        secondary: '#735c00',
        'tertiary-container': '#583c33',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#574500',
        'surface-container': '#f0eee7',
        'surface-container-low': '#f6f3ec',
        'surface-bright': '#fcf9f2',
        error: '#ba1a1a',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['Manrope', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [typography],
}
